VideoStream/streamapp/urls.py
from django.urls import path, include
from . import views

app_name = "video"
urlpatterns = [
    path('', views.index, name='index'),
    path('video_feed', views.video_feed, name='video_feed'),
    path('webcam_feed', views.webcam_feed, name='webcam_feed'),
    path('ipweblink', views.ipweblink, name='ipweblink'),
    ]

VideoStream/video_stream/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('streamapp.urls'))
]

VideoStream/streamapp/views.py
from django.shortcuts import render
from django.http.response import StreamingHttpResponse
from .camera import VideoCamera
# Create your views here.

def index(request):
	return render(request, 'streamapp/home.html')

def gen(camera):
	while True:
		frame = camera.get_frame()
		yield (b'--frame\r\n'b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')

def video_feed(request):
	return StreamingHttpResponse(gen(VideoCamera(0)),content_type='multipart/x-mixed-replace; boundary=frame')

def webcam_feed(request):
	try:
	    link = str(request.POST["link"])
	except:
		link = "http://192.168.43.1:8080/video"
	return StreamingHttpResponse(gen(VideoCamera(link)),content_type='multipart/x-mixed-replace; boundary=frame')

def ipweblink(request):
	return render(request,"streamapp/ipwebcam.html")

VideoStream/streamapp/templates/streamapp/home.html
<html>
  <head>
    <title>Video Live Stream</title>
  </head>
  <body>
    <h1>Video Live Stream</h1>
    <img src="{% url 'video:video_feed' %}">
    <img src="{% url 'video:webcam_feed' %}">
  </body>
</html>

VideoStream/streamapp/templates/streamapp/ipwebcam.html
<form action="{% url 'video:webcam_feed' %}" method="post">
    {% csrf_token %}
    Enter IpWebCam URL:<input type="text" name="link"><br>
    <input type="submit">
</form>