MyFirstSite/MyFirstSite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyFirstSite/music/urls.py
from django.urls import path
from . import views

app_name = "music"
urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('register/',views.UserFormView.as_view(),name='register'),
    path('<int:pk>/',views.DetailsView.as_view(),name='details'),
    path('album/add/',views.CreateAlbum.as_view(),name='add-album'),
    path('album/<int:pk>/',views.UpdateAlbum.as_view(),name='update-album'),
    path('album/<int:pk>/delete/',views.DeleteAlbum.as_view(),name='delete-album'),
]

MyFirstSite/music/models.py
from django.db import models
from django.urls import reverse

class Album(models.Model):
    artist = models.CharField(max_length=50)
    album_title = models.CharField(max_length=50)
    genre = models.CharField(max_length=30)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:details',kwargs={"pk":self.pk})

    def __str__(self):
        return self.album_title + ' - ' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album,on_delete=models.CASCADE)
    file_type = models.CharField(max_length=100 )
    song_title = models.CharField(max_length=100)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

MyFirstSite/music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','email','password']

MyFirstSite/music/views.py
from .models import Album,Song
from django.views import generic
from django.views.generic.edit import  CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login
from django.views.generic import View
from .forms import UserForm

class IndexView(generic.ListView):
    template_name = "music/index.html"
    context_object_name = "all_album"
    def get_queryset(self):
        return Album.objects.all()

class DetailsView(generic.DetailView):
    model = Album
    template_name = "music/details.html"
    context_object_name = "album"

class CreateAlbum(CreateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']

class UpdateAlbum(UpdateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']

class DeleteAlbum(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    #display blank form
    def get(self,request):
        form = self.form_class(None)
        return render(request,self.template_name,{'form':form})
    # when they post form process form data
    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():
            # saving data locally for cleaning, not in database
            user = form.save(commit=False)

            #cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #returns User objects if credentials are correct
            user = authenticate(username=username,password=password)

            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect('music:index')
            return render(request,self.template_name,{'form':form})

MyFirstSite/music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title%}Add Album{% endblock %}

{% block body %}
<div class="row container-fluid">
    <form class="was-validated" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% include 'music/form_template.html'%}
    </form>
</div>
{% endblock %}

MyFirstSite/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Album{% endblock %}</title>
    {% load static %}
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <style>
    body{font-family: 'Lobster', cursive;}
    </style>
</head>
<body>
<!--navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Navbar</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'music:index'%}"><i class="fas fa-compact-disc"></i>&nbsp;Album <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"><i class="fas fa-music"></i>&nbsp;Music</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-1" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0 mr-sm-2" type="submit">Search</button>
    </form>
    <ul class="navbar-nav mt-2 mt-lg-0">
    <li class="nav-item">
        <a href="{% url 'music:add-album' %}" class="nav-link mr-sm-2" >Add Album</a>
    </li>
    <li class="nav-item">
        <a href="#" class="nav-link mr-sm-2">Logout</a>
    </li>
    </ul>
  </div>
</nav>
<!--end navbar-->
<!-- Button to Open the Modal -->

{% block body %}
{% endblock %}

</body>
</html>

MyFirstSite/music/templates/music/details.html
{% extends 'music/base.html' %}
{% block title %}Album Details{% endblock %}

{% block body %}
{% if album %}
     <section>
        <div class="row container-fluid">
            <div class="col-lg-3 col-md-3">
                <div class="card m-2" >
                    <img class="card-img-top" src={{album.album_logo.url}} alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">{{ album.album_title }}</h5>
                        <p class="card-text">Artist - {{ album.artist }}<br>Genre - {{ album.genre }}</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-9 col-md-9">
                <table class="table table-striped table-dark my-2">
                    <thead>
                      <tr>
                        <th>Song Title</th>
                        <th>File Type</th>
                        <th>Favorite</th>
                      </tr>
                    </thead>
                    <tbody id="myTable">
                    {% for song in album.song_set.all%}
                    <tr>
                        <td>{{ song.song_title }}</td>
                        <td>{{ song.file_type }}</td>
                        <td>{{ song.is_favorite }}</td>
                    </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </section>
{% endif %}
{% endblock %}

MyFirstSite/music/templates/music/form_template.html
{% load crispy_forms_tags %}
  <div class="form-group">
    {% for field in form %}
    <label >{{field.label_tag}}</label>
     <div>{{field}}</div>
    <div class="valid-feedback">Valid.</div>
    <div class="invalid-feedback">Please fill out this field.</div>
    {% endfor %}
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>

MyFirstSite/music/templates/music/index.html
{% extends 'music/base.html' %}
{% block body %}

<!--albums-->
{% if all_album %}
    <section>
        <div class="row container-fluid">
            {% for album in all_album %}
            <div class="col-sm-4 col-lg-4 col-12">
                <div class="card m-2" >
                    <img class="card-img-top" src={{album.album_logo.url}} alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">{{ album.album_title }}</h5>
                        <p class="card-text">Artist - {{ album.artist }}<br>Genre - {{ album.genre }}</p>
                        <a href="{% url 'music:details' album.id %}" class="btn btn-primary">Songs</a>
                        <div style="display: inline-block;">
                        <form action="{% url 'music:delete-album' album.id %}" method="post" >
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger"><i class="fas fa-trash-alt"></i></button>
                        </form>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>
{% else %}
     <h4>You don't have any album</h4>
{% endif %}
<!--end albums-->


{% endblock %}

MyFirstSite/music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title%}Register{% endblock %}

{% block body %}
<div class="row container-fluid">
    <form class="was-validated" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% include 'music/form_template.html'%}
    </form>
</div>
{% endblock %}